"""add_v2_columns

Revision ID: 292ec41c805c
Revises: 3e9c3e5bb48a
Create Date: 2026-04-25 12:39:19.806588
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '292ec41c805c'
down_revision: Union[str, None] = '3e9c3e5bb48a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backup_history', sa.Column('stage', sa.String(length=50), nullable=True))
    op.add_column('backup_history', sa.Column('checksum', sa.String(length=64), nullable=True))
    op.add_column('backup_schedules', sa.Column('retention_daily', sa.Integer(), nullable=False))
    op.add_column('backup_schedules', sa.Column('retention_weekly', sa.Integer(), nullable=False))
    op.add_column('backup_schedules', sa.Column('retention_monthly', sa.Integer(), nullable=False))
    op.add_column('servers', sa.Column('environment', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'environment')
    op.drop_column('backup_schedules', 'retention_monthly')
    op.drop_column('backup_schedules', 'retention_weekly')
    op.drop_column('backup_schedules', 'retention_daily')
    op.drop_column('backup_history', 'checksum')
    op.drop_column('backup_history', 'stage')
    # ### end Alembic commands ###
