"""initial tables

Revision ID: 3e9c3e5bb48a
Revises: 
Create Date: 2026-04-24 07:22:27.316571
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '3e9c3e5bb48a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
